package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/sebastianfs82/terraform-provider-komodo/internal/client"
)

var _ datasource.DataSource = &TagDataSource{}

func NewTagDataSource() datasource.DataSource {
	return &TagDataSource{}
}

type TagDataSource struct {
	client *client.Client
}

type TagDataSourceModel struct {
	ID    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Color types.String `tfsdk:"color"`
	Owner types.String `tfsdk:"owner" computed:"true"`
}

func (d *TagDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tag"
}

func (d *TagDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Reads an existing Komodo tag by id or name.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The tag id (ObjectId). If set, takes precedence over name.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The tag name.",
			},
			"color": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The tag color.",
			},
			"owner": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The owner id (auto-generated by Komodo API).",
			},
		},
	}
}

func (d *TagDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *TagDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data TagDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data.ID.ValueString() == "" && data.Name.ValueString() == "" {
		resp.Diagnostics.AddError("Missing Query Attribute", "Either id or name must be set to query a tag.")
		return
	}
	var tag *client.Tag
	var err error
	if data.ID.ValueString() != "" {
		// Lookup by ID
		tags, listErr := d.client.ListTags(ctx)
		if listErr != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to list tags: %s", listErr))
			return
		}
		for _, t := range tags {
			if t.ID.OID == data.ID.ValueString() {
				tag = &t
				break
			}
		}
		if tag == nil {
			resp.Diagnostics.AddError("Not Found", fmt.Sprintf("Tag with id %s not found", data.ID.ValueString()))
			return
		}
	} else {
		// Lookup by name
		tag, err = d.client.GetTag(ctx, data.Name.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read tag, got error: %s", err))
			return
		}
		if tag == nil {
			resp.Diagnostics.AddError("Not Found", fmt.Sprintf("Tag with name %s not found", data.Name.ValueString()))
			return
		}
	}
	data.ID = types.StringValue(tag.ID.OID)
	data.Name = types.StringValue(tag.Name)
	data.Color = types.StringValue(tag.Color)
	data.Owner = types.StringValue(tag.Owner)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
