// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/sebastianfs82/terraform-provider-komodo/internal/client"
)

var _ resource.Resource = &TagResource{}
var _ resource.ResourceWithImportState = &TagResource{}

func NewTagResource() resource.Resource {
	return &TagResource{}
}

type TagResource struct {
	client *client.Client
}

type TagResourceModel struct {
	ID    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Color types.String `tfsdk:"color"`
	Owner types.String `tfsdk:"owner" computed:"true"`
}

func (r *TagResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tag"
}

func (r *TagResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Komodo tag.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The Terraform resource ID (ObjectId).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The tag name.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"color": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The tag color.",
			},
			"owner": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The owner id (auto-generated by Komodo API).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *TagResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = c
}

func (r *TagResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data TagResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Creating tag", map[string]interface{}{
		"name":  data.Name.ValueString(),
		"color": data.Color.ValueString(),
		"owner": data.Owner.ValueString(),
	})
	createReq := client.CreateTagRequest{
		Name:  data.Name.ValueString(),
		Color: data.Color.ValueString(),
		Owner: data.Owner.ValueString(),
	}
	tag, err := r.client.CreateTag(ctx, createReq)
	if err != nil {
		if strings.Contains(err.Error(), "multiple tags found") {
			resp.Diagnostics.AddError(
				"Ambiguous Tag Name",
				fmt.Sprintf("Multiple tags exist with the name %q (case-insensitive). Please ensure tag names are unique (case-insensitive) in Komodo for Terraform management.", data.Name.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create tag, got error: %s", err))
		return
	}
	tflog.Debug(ctx, "API returned tag ID", map[string]interface{}{
		"tag_id": tag.ID.OID,
	})
	if tag.ID.OID == "" {
		resp.Diagnostics.AddError(
			"Tag creation failed: missing ID",
			"The Komodo API did not return a tag ID. Resource cannot be tracked in state.",
		)
		return
	}
	data.ID = types.StringValue(tag.ID.OID)
	data.Name = types.StringValue(tag.Name)
	data.Color = types.StringValue(tag.Color)
	data.Owner = types.StringValue(tag.Owner)
	tflog.Trace(ctx, "Created tag resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data TagResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var tag *client.Tag
	var err error
	if data.ID.ValueString() != "" {
		// Try to find by ID first
		tags, listErr := r.client.ListTags(ctx)
		if listErr != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to list tags: %s", listErr))
			return
		}
		for _, t := range tags {
			if t.ID.OID == data.ID.ValueString() {
				tag = &t
				break
			}
		}
		if tag == nil {
			tflog.Debug(ctx, "Tag not found by ID, removing from state", map[string]interface{}{"id": data.ID.ValueString()})
			resp.State.RemoveResource(ctx)
			return
		}
	} else if data.Name.ValueString() != "" {
		// Fallback to name lookup
		tag, err = r.client.GetTag(ctx, data.Name.ValueString())
		if err != nil {
			if strings.Contains(err.Error(), "no tag found") {
				tflog.Debug(ctx, "Tag not found by name, removing from state", map[string]interface{}{"name": data.Name.ValueString()})
				resp.State.RemoveResource(ctx)
				return
			}
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read tag by name, got error: %s", err))
			return
		}
	} else {
		resp.Diagnostics.AddError("Missing Resource Identifiers", "Both ID and Name are empty in state.")
		return
	}
	data.ID = types.StringValue(tag.ID.OID)
	data.Name = types.StringValue(tag.Name)
	data.Color = types.StringValue(tag.Color)
	data.Owner = types.StringValue(tag.Owner)
	tflog.Debug(ctx, "Read tag resource", map[string]interface{}{"id": tag.ID.OID, "name": tag.Name, "color": tag.Color, "owner": tag.Owner})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data TagResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	updateReq := client.CreateTagRequest{
		Name:  data.Name.ValueString(),
		Color: data.Color.ValueString(),
	}
	tag, err := r.client.UpdateTag(ctx, data.Name.ValueString(), updateReq)
	if err != nil {
		if strings.Contains(err.Error(), "multiple tags found") {
			resp.Diagnostics.AddError(
				"Ambiguous Tag Name",
				fmt.Sprintf("Multiple tags exist with the name %q (case-insensitive). Please ensure tag names are unique (case-insensitive) in Komodo for Terraform management.", data.Name.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update tag, got error: %s", err))
		return
	}
	data.ID = types.StringValue(tag.ID.OID)
	data.Name = types.StringValue(tag.Name)
	data.Color = types.StringValue(tag.Color)
	data.Owner = types.StringValue(tag.Owner)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data TagResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Deleting tag", map[string]interface{}{
		"id": data.ID.ValueString(),
	})
	err := r.client.DeleteTag(ctx, data.ID.ValueString())
	if err != nil {
		if strings.Contains(err.Error(), "multiple tags found") {
			resp.Diagnostics.AddError(
				"Ambiguous Tag Name",
				fmt.Sprintf("Multiple tags exist with the name %q (case-insensitive). Please ensure tag names are unique (case-insensitive) in Komodo for Terraform management before deleting.", data.ID.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete tag, got error: %s", err))
		return
	}
	tflog.Trace(ctx, "Deleted tag resource")
}

func (r *TagResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
